title: Willie Loftie-Eaton
email: willieloea@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  my little corner of the internet
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://willieloea.github.io"
twitter_username: willieloea
github_username:  willieloea

# Build settings
theme: minima
plugins:
  - jekyll-feed
permalink: /blog/:title
